spring.application.name=payment-gateway
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_gateway}
spring.datasource.username=${DB_USERNAME:payment_gateway}
spring.datasource.password=${DB_PASSWORD:payment_gateway}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

app.security.demo-client-id=${DEMO_CLIENT_ID:demo-client}
app.security.demo-client-secret=${DEMO_CLIENT_SECRET:change-me}
app.security.jwt-secret=${JWT_SECRET:VGhpcy1pcy1hLWRlbW8tc2VjcmV0LWtleS10aGF0LWlzLTMyaXRlcw==}
app.security.jwt-ttl=${JWT_TTL:PT1H}
